# Generated by Django 4.2.7 on 2025-10-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('variables', models.JSONField(default=dict, verbose_name='环境变量')),
                ('headers', models.JSONField(default=dict, verbose_name='默认请求头')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
