# Generated by Django 4.2.7 on 2025-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='parameterized_data',
            field=models.JSONField(default=list, verbose_name='参数化内容'),
        ),
        migrations.AddField(
            model_name='environment',
            name='post_hook',
            field=models.TextField(blank=True, null=True, verbose_name='后置钩子函数'),
        ),
        migrations.AddField(
            model_name='environment',
            name='pre_hook',
            field=models.TextField(blank=True, null=True, verbose_name='前置钩子函数'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='配置描述'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='headers',
            field=models.JSONField(default=dict, verbose_name='公共请求头'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='variables',
            field=models.JSONField(default=dict, verbose_name='局部变量'),
        ),
    ]
