# Generated by Django 4.2.7 on 2025-11-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_environment_parameterized_data_environment_post_hook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识不同的 Token，如：API Token、登录 Token 等', max_length=100, verbose_name='Token 名称')),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('drf_token', 'Django REST Framework Token'), ('header', '自定义 Header')], default='bearer', max_length=20, verbose_name='认证类型')),
                ('token', models.TextField(help_text='Token 的实际值，支持变量 ${variable}', verbose_name='Token 值')),
                ('header_name', models.CharField(default='Authorization', help_text='当认证类型为自定义 Header 时使用', max_length=100, verbose_name='Header 名称')),
                ('token_format', models.CharField(default='Bearer', help_text='Token 的前缀，如 Bearer、Token 等，留空则不加前缀', max_length=50, verbose_name='Token 格式')),
                ('description', models.TextField(blank=True, help_text='说明这个 Token 的用途', null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, help_text='启用后，接口未配置认证时会自动使用此 Token', verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='如果有多个 Token，默认使用此 Token', verbose_name='默认 Token')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='如果 Token 值中包含变量，可以在这里配置变量值', verbose_name='变量配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局 Token',
                'verbose_name_plural': '全局 Token',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
