# Generated by Django 4.2.7 on 2025-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='body_override',
            field=models.JSONField(blank=True, default=dict, help_text='覆盖接口定义的请求体，支持${variable}变量，留空则使用接口定义的请求体', verbose_name='请求体覆盖（支持变量）'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='headers_override',
            field=models.JSONField(blank=True, default=dict, help_text='覆盖接口定义的请求头，支持${variable}变量，留空则使用接口定义的请求头', verbose_name='请求头覆盖（支持变量）'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='params_override',
            field=models.JSONField(blank=True, default=dict, help_text='覆盖接口定义的查询参数，支持${variable}变量，留空则使用接口定义的查询参数', verbose_name='查询参数覆盖（支持变量）'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='url_override',
            field=models.CharField(blank=True, help_text='覆盖接口定义的URL，支持${variable}变量，留空则使用接口定义的URL', max_length=500, null=True, verbose_name='URL覆盖（支持变量）'),
        ),
    ]
