# Generated by Django 4.2.7 on 2025-11-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_api_parameterized_data_api_parameterized_mode'),
        ('projects', '0001_initial'),
        ('environments', '0003_globaltoken'),
        ('testcases', '0003_add_parameterized_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='性能测试名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='测试描述')),
                ('threads', models.IntegerField(default=10, help_text='同时运行的虚拟用户数', verbose_name='并发线程数')),
                ('ramp_up', models.IntegerField(default=10, help_text='所有线程启动完成所需的时间', verbose_name='启动时间(秒)')),
                ('duration', models.IntegerField(default=60, help_text='测试持续运行的时间，0表示使用循环次数', verbose_name='持续时间(秒)')),
                ('loops', models.IntegerField(default=1, help_text='每个线程执行的次数，-1表示无限循环', verbose_name='循环次数')),
                ('jmx_file', models.CharField(blank=True, help_text='自定义JMX文件路径，留空则自动生成', max_length=500, null=True, verbose_name='JMX文件路径')),
                ('last_result', models.JSONField(blank=True, default=dict, null=True, verbose_name='最新执行结果')),
                ('last_execution_time', models.DateTimeField(blank=True, null=True, verbose_name='最新执行时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_tests', to='apis.api', verbose_name='关联接口')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.environment', verbose_name='测试环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_tests', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '性能测试',
                'verbose_name_plural': '性能测试',
                'ordering': ['-created_at'],
            },
        ),
    ]
