# Generated by Django 4.2.25 on 2025-11-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="渠道名称")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("wecom", "企业微信"),
                            ("dingtalk", "钉钉"),
                            ("feishu", "飞书"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=20,
                        verbose_name="渠道类型",
                    ),
                ),
                ("webhook_url", models.URLField(verbose_name="Webhook URL")),
                (
                    "secret",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="加签密钥"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "notify_on_success",
                    models.BooleanField(default=False, verbose_name="成功时通知"),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(default=True, verbose_name="失败时通知"),
                ),
                (
                    "notify_on_complete",
                    models.BooleanField(default=False, verbose_name="完成时通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知渠道",
                "verbose_name_plural": "通知渠道",
                "ordering": ["-created_at"],
            },
        ),
    ]
