# Generated by Django 4.2.7 on 2025-10-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('url', models.CharField(max_length=500, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('description', models.TextField(blank=True, null=True, verbose_name='接口描述')),
                ('headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('params', models.JSONField(default=dict, verbose_name='查询参数')),
                ('body', models.JSONField(default=dict, verbose_name='请求体')),
                ('auth_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='认证类型')),
                ('auth_config', models.JSONField(default=dict, verbose_name='认证配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'ordering': ['-created_at'],
            },
        ),
    ]
