# Generated by Django 4.2.7 on 2025-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='parameterized_data',
            field=models.JSONField(blank=True, default=list, help_text='格式: [{"param1": "value1"}, {"param1": "value2"}]，每个字典代表一组参数', verbose_name='参数化数据'),
        ),
        migrations.AddField(
            model_name='api',
            name='parameterized_mode',
            field=models.CharField(choices=[('disabled', '禁用'), ('enabled', '启用')], default='disabled', help_text='启用后，接口将使用参数化数据循环执行多次', max_length=20, verbose_name='参数化模式'),
        ),
    ]
