# Generated by Django 4.2.7 on 2025-10-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套件描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.environment', verbose_name='测试环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuites', to='projects.project', verbose_name='所属项目')),
                ('testcases', models.ManyToManyField(related_name='testsuites', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
    ]
