# Generated by Django 4.2.25 on 2025-11-05 01:55

from django.db import migrations, models
import django.db.models.deletion


def migrate_testcases_to_through_table(apps, schema_editor):
    """将现有的测试套件-测试用例关联迁移到新的中间表"""
    TestSuite = apps.get_model('testsuites', 'TestSuite')
    TestSuiteTestCase = apps.get_model('testsuites', 'TestSuiteTestCase')
    
    # 获取所有测试套件
    for suite in TestSuite.objects.all():
        # 获取旧的M2M关联
        old_testcases = suite.testcases.through.objects.filter(testsuite_id=suite.id)
        # 为每个关联创建新的中间表记录
        for idx, relation in enumerate(old_testcases, start=1):
            TestSuiteTestCase.objects.get_or_create(
                testsuite_id=suite.id,
                testcase_id=relation.testcase_id,
                defaults={'order': idx}
            )


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0005_testcase_files_override"),
        ("testsuites", "0001_initial"),
    ]

    operations = [
        # 第1步：创建新的中间表
        migrations.CreateModel(
            name="TestSuiteTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "testsuite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testsuites.testsuite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "套件用例关联",
                "verbose_name_plural": "套件用例关联",
                "ordering": ["order", "id"],
                "unique_together": {("testsuite", "testcase")},
            },
        ),
        # 第2步：迁移数据
        migrations.RunPython(migrate_testcases_to_through_table, migrations.RunPython.noop),
        # 第3步：删除旧的M2M字段
        migrations.RemoveField(
            model_name='testsuite',
            name='testcases',
        ),
        # 第4步：重新创建M2M字段（带through参数）
        migrations.AddField(
            model_name='testsuite',
            name='testcases',
            field=models.ManyToManyField(
                related_name="testsuites",
                through="testsuites.TestSuiteTestCase",
                to="testcases.testcase",
                verbose_name="测试用例",
            ),
        ),
    ]
