# Generated by Django 4.2.7 on 2025-10-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testsuites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('cron_expression', models.CharField(max_length=100, verbose_name='Cron表达式')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '停用')], default='active', max_length=20, verbose_name='任务状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project', verbose_name='所属项目')),
                ('testsuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='testsuites.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
