# Generated by Django 4.2.7 on 2025-10-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='执行状态')),
                ('result', models.JSONField(default=dict, verbose_name='执行结果')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='projects.project', verbose_name='所属项目')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='testcases.testcase', verbose_name='测试用例')),
                ('testsuite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='testsuites.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ['-created_at'],
            },
        ),
    ]
