# Generated by Django 4.2.7 on 2025-11-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='execution_type',
            field=models.CharField(choices=[('normal', '普通执行'), ('parameterized', '参数化执行'), ('suite', '套件执行')], default='normal', max_length=20, verbose_name='执行类型'),
        ),
        migrations.AddField(
            model_name='execution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='executions.execution', verbose_name='父执行记录'),
        ),
    ]
